# Generated by Django 5.0.2 on 2024-02-29 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livechatapp', '0002_user_remove_message_room_remove_message_sender_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
