# Generated by Django 5.0.2 on 2024-03-08 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livechatapp', '0005_alter_userprofile_profile_follow'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=10)),
                ('follow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livechatapp.follow')),
            ],
        ),
    ]
